<?php

return [
    'arrivals' => [
        'Иркутск',
        'Чита',
        'Кяхта',
        'Закаменск',
    ],
    'autovokzal' => [
        'stations' => [
            'ulan-ude--turuntaevo' => [
                'name' => 'Автовокзал «Улан-Удэ — Турунтаево»',
                'address' => 'г. Улан-Удэ, ул. Ботаническая, 35в/3',
                'dispatcherPhone' => '+7 (924) 457-57-24',
                'openingHours' => '07:30–19:00',
                'lunch' => '11:00–12:00',
                'backgroundLink' => '/img/stations/turuntaevo-150x150.jpg',
                'modalImageLink' => '/img/stations/turuntaevo-540x340.jpg',
            ],
            'ulan-ude-baikal' => [
                'name' => 'Автовокзал в Улан-Удэ «Байкал»',
                'address' => 'г. Улан-Удэ, ул. Советская 1б',
                'dispatcherPhone' => '+7 (3012) 717-717',
                'openingHours' => '07:30–19:00',
                'lunch' => '12:00–13:00',
                'backgroundLink' => '/img/stations/2018-01-09_11-21-47_1-150x150.jpg',
                'modalImageLink' => '/img/stations/2018-01-09_11-21-47_1-540x340.jpg',
            ],
            'ulan-ude-railroad' =>[
                'name' => 'Автовокзал в Улан-Удэ на ЖД вокзале',
                'address' => 'г. Улан-Удэ, ул. Ботаническая, 68/2',
                'dispatcherPhone' => '+7 (924) 458-48-88',
                'openingHours' => '07:45–21:00',
                'lunch' => '14:20–14:50',
                'backgroundLink' => '/img/stations/zhd-150x150.jpg',
                'modalImageLink' => '/img/stations/zhd-540x340.jpg',
            ],
            'ulan-ude--zaigraevo' => [
                'name' => 'Автовокзал Улан-Удэ — Заиграево, на Мелькомбинате',
                'address' => 'г. Улан-Удэ, ул. Пищевая, 1в/1',
                'dispatcherPhone' => '+7 (924) 457-57-24',
                'openingHours' => '07:00–21:00',
                'lunch' => '',
                'backgroundLink' => '/img/stations/zaigraevo-150x150.jpg',
                'modalImageLink' => '/img/stations/zaigraevo-540x340.jpg',
            ],
            'ulan-ude--novoilinsk' =>[
                'name' => 'Автовокзал Улан-Удэ — Новоильинск',
                'address' => 'г. Улан-Удэ, ул. Пищевая, 1г/1',
                'dispatcherPhone' => '+7 (9021) 67-02-26',
                'openingHours' => '07:00–20:00',
                'lunch' => '12:00–13:00',
                'backgroundLink' => '/img/stations/novoilinsk-150x150.jpg',
                'modalImageLink' => '/img/stations/novoilinsk-540x340.jpg',
            ],
            'barguzin--ulan-ude' => [
                'name' => 'Автокасса «Баргузин — Улан-Удэ»',
                'address' => 'с. Баргузин, Центр',
                'dispatcherPhone' => '+7 (924) 35-25-255',
                'openingHours' => '08:00–16:30, в выходные дни: 08:00–16:00',
                'lunch' => '13:00–14:00',
                'backgroundLink' => '/img/stations/brz_prev-150x150.jpg',
                'modalImageLink' => '/img/stations/brz_bg-540x204.jpg',
            ],
            'goryachinsk--ulan-ude' =>[
                'name' => 'Автокасса «Горячинск — Улан-Удэ»',
                'address' => 'с. Горячинск, ул. Октябрьская 15в',
                'dispatcherPhone' => '+7 (9025) 30-10-10',
                'openingHours' => '09:00–18:00',
                'lunch' => '13:00-14:00',
                'backgroundLink' => '/img/stations/txm4_umomdi-150x150.jpg',
                'modalImageLink' => '/img/stations/txm4_umomdi-540x340.jpg',
            ],
            'kabansk--ulan-ude' =>[
                'name' => 'Автокасса «Кабанск — Улан-Удэ»',
                'address' => 'пгт. Кабанск, ул. Кооперативная 32',
                'dispatcherPhone' => '+7 (9021) 60-07-47',
                'openingHours' => '07:00–19:00',
                'lunch' => '',
                'backgroundLink' => '/img/stations/kabansk-150x150.jpg',
                'modalImageLink' => '/img/stations/kabansk-540x340.jpg',
            ],
            'kiren--ulan-ude' =>[
                'name' => 'Автокасса «Кырен — Улан-Удэ»',
                'address' => 'с. Кырен, ул. Ленина 93',
                'dispatcherPhone' => '+7 (950) 055‒79‒18',
                'openingHours' => '08:30–17:00',
                'lunch' => '13:00–14:00',
                'backgroundLink' => '/img/stations/krn-uu-150x150.jpg',
                'modalImageLink' => '/img/stations/krn-uu-540x340.jpg',
            ],
            'muhorshibir--ulan-ude' =>[
                'name' => 'Автокасса «Мухоршибирь — Улан-Удэ»',
                'address' => 'с. Мухоршибирь, Центр',
                'dispatcherPhone' => '+7 (902) 450-56-72',
                'openingHours' => '07:00–17:00',
                'lunch' => '',
                'backgroundLink' => '/img/stations/image-21-06-23-12-14-2-150x150.jpeg',
                'modalImageLink' => '/img/stations/image-21-06-23-12-14-2-540x340.jpeg',
            ],
            'novoilinsk--ulan-ude' =>[
                'name' => 'Автокасса «Новоильинск — Улан-Удэ»',
                'address' => 'с. Новоильинск, ул. Ленина 16',
                'dispatcherPhone' => '+7 (9021) 67-02-26',
                'openingHours' => '06:00–18:30',
                'lunch' => '12:30–13:30',
                'backgroundLink' => '/img/stations/novoilinsk_prev-150x150.jpg',
                'modalImageLink' => '/img/stations/novoilinsk_uu-540x340.jpg',
            ],
            'selenginsk--ulan-ude' =>[
                'name' => 'Автокасса «Селенгинск — Улан-Удэ»',
                'address' => 'пгт. Селенгинск, Торговая площадь, 15м на юго-восток от здания с почтовым адресом п.Селенгинск, мкр-н Березовый 6/2',
                'dispatcherPhone' => '+7 (9021) 60-04-38',
                'openingHours' => '06:00–19:30, в выходные дни: 07:00–19:30',
                'lunch' => '',
                'backgroundLink' => '/img/stations/selenginsk_prev-150x150.jpg',
                'modalImageLink' => '/img/stations/selenginsk-540x340.jpg',
            ],
            'sosnovo-ozerskoe--ulan-ude' =>[
                'name' => 'Автокасса «Сосново-Озёрское — Улан-Удэ»',
                'address' => 'с. Сосново-Озерское, ул. Первомайская 115Б',
                'dispatcherPhone' => '+7 (914) 833-66-66',
                'openingHours' => '07:30–11:00, 13:30–17:00',
                'lunch' => '11:00–13:30',
                'backgroundLink' => '/img/stations/image-26-06-23-11-43-1-150x150.png',
                'modalImageLink' => '/img/stations/image-26-06-23-11-43-1-540x340.png',
            ],
            'turuntaevo--ulan-ude' =>[
                'name' => 'Автокасса «Турунтаево — Улан-Удэ»',
                'address' => 'с. Турунтаево, ул. Оболенского 8а',
                'dispatcherPhone' => '+7 (924) 356-71-77',
                'openingHours' => '07:00–19:00, в выходные дни: 07:00–17:00',
                'lunch' => '13:00–14:00',
                'backgroundLink' => '/img/stations/trntv-uu-150x150.jpg',
                'modalImageLink' => '/img/stations/trntv-uu-540x340.jpg',
            ],
            'ust-barguzin--ulan-ude' =>[
                'name' => 'Автокасса «Усть-Баргузин — Улан-Удэ»',
                'address' => 'пгт. Усть-Баргузин, ул. Энгельса, 44',
                'dispatcherPhone' => '+7 (9021) 61-23-22',
                'openingHours' => '10:00–15:00',
                'lunch' => '',
                'backgroundLink' => '/img/stations/img_4673-150x150.webp',
                'modalImageLink' => '/img/stations/img_4673-540x340.webp',
            ],
            'horinsk--ulan-ude' =>[
                'name' => 'Автокасса «Хоринск — Улан-Удэ»',
                'address' => 'с. Хоринск, Первомайская улица, 43',
                'dispatcherPhone' => '+7 (983) 637-79-41',
                'openingHours' => '08:00–18:00',
                'lunch' => '',
                'backgroundLink' => '/img/stations/horinsk-150x150.jpg',
                'modalImageLink' => '/img/stations/horinsk-540x340.jpg',
            ],
        ],
        'infoPhone' => '+7 (9021) 66-80-03',
    ],
];
